# Generated by Django 5.2.4 on 2025-08-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_class', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TimeField()),
            ],
        ),
    ]
