# Generated by Django 5.2.4 on 2025-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_alter_registration_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('s_city', models.CharField(max_length=20)),
                ('s_class', models.CharField(max_length=10)),
            ],
        ),
    ]
